---
# tasks file for hoplacloud.ansible-role-veeam-api-create-customer
- name: Get token
  ansible.builtin.uri:
    url: "{{url_api}}/token"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: password
      username: "{{vcc_username}}"
      password: "{{vcc_password}}"
  register: token

- name: Set token to fact
  set_fact:
    accessToken: "Bearer {{token.json.access_token}}"

- name: Create new company
  uri:
    url: "{{url_api}}/organizations/companies"
    method: POST
    body_format: json
    body:
      resellerUid: null
      organizationInput:
        name: "{{nom_client}}"
        email: "{{mail_client}}"
        notes: null
      subscriptionPlanUid: null
      permissions: []
      IsAlarmDetectEnabled: false
    headers:
      Content-Type: application/json
      Authorization: "{{accessToken}}"
  register: company

- name: Set instaceUid of new company to fact
  set_fact:
    instanceUid: "{{company.json.data.instanceUid}}"

- name: Assign company to site and create user
  uri:
    url: "{{url_api}}/organizations/companies/{{instanceUid}}/sites"
    method: POST
    body_format: json
    body:
      siteUid: "{{siteUid}}"
      cloudTenantType: General
      leaseExpirationEnabled: false
      leaseExpirationDate:
      ownerCredentials:
        userName: "{{nom_client}}"
        password: "{{client_password}}"
      description: Created by API.
      throttlingEnabled: false
      maxConcurrentTask: "{{maxConcurrentTask}}"
      gatewaySelectionType: StandaloneGateways
      gatewayPoolsUids:
      isGatewayFailoverEnabled: false
    status_code: 202
    headers:
      Content-Type: application/json
      Authorization: "{{accessToken}}"

- name: Wait active status for company
  uri:
    url: "{{url_api}}/organizations/companies/{{instanceUid}}"
    method: GET
    headers:
      Content-Type: application/json
      Authorization: "{{accessToken}}"
  register: status
  until: status.json.data.status == "Active"
  retries: 20
  delay: 10

- name: Enabling backup ressources + set storage quota
  uri:
    url: "{{url_api}}/organizations/companies/{{instanceUid}}/sites/{{siteUid}}/BackupResources"
    method: POST
    body_format: json
    body:
      repositoryUid: fa039845-2bba-4ea7-bcfe-a418fc854f33
      cloudRepositoryName: backup-fr-east-1
      storageQuota: "{{quotas}}"
      serversQuota: "{{max_servers}}"
      isServersQuotaUnlimited: true
      workstationsQuota:
      isWorkstationsQuotaUnlimited: true
      vmsQuota:
      isVmsQuotaUnlimited: true
      isWanAccelerationEnabled: false
      wanAcceleratorUid:
      isDefault: false
    status_code: 202
    headers:
      Content-Type: application/json
      Authorization: "{{accessToken}}"
