---
# tasks file for hoplacloud.ansible-role-veeam-api-create-customer
- name: Get token
  ansible.builtin.uri:
    url: "{{url_api}}/token"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: password
      username: "{{vcc_username}}"
      password: "{{vcc_password}}"
  register: token

- name: Set token to fact
  set_fact:
    accessToken: "Bearer {{token.json.access_token}}"

- name: Create new company
  uri:
    url: "{{url_api}}/organizations/companies"
    method: POST
    body_format: json
    body:
      resellerUid: null
      organizationInput:
        name: "{{nom_client}}"
        email: "{{mail_client}}"
        notes: null
      subscriptionPlanUid: null
      permissions: []
      IsAlarmDetectEnabled: false
  register: company

- name: Set instaceUid of new company to fact
  set_fact:
    instanceUid: "{{company.json.data.instanceUid}}"
